### ISSUE TITLE
bug: panic at src/runner/step_runner.rs:32:56

### ISSUE THREAD

**Issue by mzsrtgzr2** [cocmd/cocmd#32]
**Describe the bug**

running rust.setup-wasm

gitdb git:(main) ✗ cocmd browse         
install Rust
Rust is already installed, skipping...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IO(Custom { kind: NotConnected, error: "not a terminal" })', src/runner/step_runner.rs:32:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
❌ Failed (stderr):
Install WASM runtime
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
Install WASM runtime
    Updating crates.io index
     Ignored package `wasm-pack v0.12.1` is already installed, use --force to override

**To Reproduce**
1.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Setup information**
- OS: What OS are you using?
- Version: which version of Cocmd are you running? (you can find out by running `cocmd --version` inside a terminal)

**Comment by mzsrtgzr2** [comment]
already fixed
